# Your Name or Company
title: Labdhi Ghelani


# Description of your website. This is used for social sharing.
description:  Resume 
# A brief blurb about yourself
content: Hi, I am a Data Analysis Enthusiast with a passion for science and technology aspiring to work in a challenging environment to bring to life the stories underlying seemingly unintelligible data.
# Add your social links
social:
  - platform: Github
    url: https://github.com/labdhi-ghelani
  - platform: Linkedin
    url: https://www.linkedin.com/in/labdhi-ghelani/
  - platform: Tableau
    url: https://public.tableau.com/profile/labdhi.ghelani#!/
  - platform: RPubs
    url: https://rpubs.com/labdhi-ghelani

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
