# Your Name or Company
title: Labdhi Ghelani
<h2>Data Analytics Graduate Student at Northeastern University</h2>

# Description of your website. This is used for social sharing.
description:  Resume 
# A brief blurb about yourself
content: Hi, I am a Data Analysis Enthusiast with a passion for science and technology aspiring to work in a challenging environment to bring to life the stories underlying seemingly unintelligible data.
# Add your social links
social:
  - platform: github
    url: https://github.com/brianmaierjr
  - platform: linkedin
    url: https://facebook.com/brianmaierjr
  - platform: Tableau
    url: https://twitter.com/brianmaierjr
  - platform: RPubs
    url: brianmaierjr

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
